#! /bin/bash

vncserver -kill :1
sleep .5
vncserver :1 -geometry 1024x768 -alwaysshared &
sleep .5

export DISPLAY=:1
xsetroot -solid '#000080'
wmaker &
firefox &
xclock -geometry -0-0 -digital -update 1&
xterm &

